version: '3'

services:
  client:
    build:
      context: ./
      dockerfile: docker/client/Dockerfile
    volumes:
      - ./:/var/www
      - /var/www/node_modules
    environment:
      - APP_ENV=${APP_ENV:-production}
    command: ./bin/client.sh

  app:
    build:
      context: ./
      dockerfile: docker/app/Dockerfile
    volumes:
      - ./:/var/www
      - /var/www/vendor

  nginx:
    image: 'nginx:latest'
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${NGINX_PORT:-8080}:80
    depends_on:
      - client
      - app
